name: CI

on: [push, pull_request]

jobs:
    build:
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest, macOS-latest]
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v3

            - name: Setup .NET
              uses: actions/setup-dotnet@v3
              with:
                  dotnet-version: 7.0.x

            - name: Build
              if: runner.os != 'Windows'
              run: |
                  chmod +x ./build.sh
                  ./build.sh DotnetBuild
              env:
                  CI: true

            - name: Build
              if: runner.os == 'Windows'
              run: ./build.cmd DotnetBuild
              env:
                  CI: true

            - name: Formatting
              if: runner.os != 'Windows'
              run: |
                  chmod +x ./build.sh
                  ./build.sh checkFormatCode
              env:
                  CI: true

            - name: Formatting
              if: runner.os == 'Windows'
              run: ./build.cmd checkFormatCode
              env:
                  CI: true

    test:
        strategy:
        runs-on: self-hosted
        steps:
            - uses: actions/checkout@v3

            - name: Test
              if: runner.os != 'Windows'
              run: |
                  chmod +x ./build.sh
                  ./build.sh DotnetTest
              env:
                  CI: true

            - name: Test
              if: runner.os == 'Windows'
              run: ./build.cmd DotnetTest
              env:
                  CI: true
